---
- name: Bambini
  hosts: installer-uefi,installer-bios
  environment:
    PATH: /local/conda/envs/bambini-python/sbin:/local/conda/envs/bambini-python/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
    CONDA_PREFIX: /local/conda/envs/bambini-python
  tasks:
    - name: Import role bambini
      ansible.builtin.import_role:
        name: geertsky.bambini.ansible_bambini
